use_frameworks!

platform :ios, '12.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Xcode 14.3移除ARC库, target version < 9.0的pod库会报找不到arc文件夹
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

target 'XXTableViewForm_Example' do
  pod 'XXTableViewForm', :path => '../'

  target 'XXTableViewForm_Tests' do
    inherit! :search_paths

    #pod 'Kiwi'
    #pod 'FBSnapshotTestCase'
    pod 'Quick'
    pod 'Nimble'

  end
end
